GET http://localhost:3002/venues

###

POST http://localhost:3002/venue/new
Content-Type: application/json

{
  "type": "Cosy Pub",
  "name": "The Royal Oak",
  "location": "London",
  "image": "http://www.royaloaklondon.co.uk/wp-content/uploads/2014/10/royal-oak-1.jpg"
}

###

DELETE http://localhost:3002/venue/delete/64483b0a84364d59184beb66
###

DELETE http://localhost:3002/venue/deleteall
###

PUT http://localhost:3002/venue/vibes/647915141d8c2f09ee63f074
Content-Type: application/json

{
  "vibes": 5
}

###

GET  http://localhost:3002/users

###

POST http://localhost:3002/signup
Content-Type: application/json

{
  "username": "SilkyBoy",
  "email": "joe+1@gmail.com",
  "password": "12345"
}

###

POST http://localhost:3002/login
Content-Type: application/json

{
  "email": "joe+1@gmail.com",
  "password": "12345"
}

###

DELETE http://localhost:3002/user/delete/643471bdb737979400b6e794

###

PUT http://localhost:3002/user/6434739bce409558743bfee9
Content-Type: application/json

{
  "type": "Club Night"
}

###

DELETE http://localhost:3002/users/deleteall